### ISSUE TITLE
fucntion levenshteinSim() not found

### ISSUE THREAD

**Issue by Akshay-A-Kulkarni** [Akshay-A-Kulkarni/MSstatsQCgui_v2.0#1]
levenshteinSim() used in guess-col-names fucntion in data-validation.R seems to be causing issue while uploading files

**Comment by eralpdogu** [comment]
This function should be in Package 'RecordLinkage'

**Comment by Akshay-A-Kulkarni** [comment]
The original packages uses C compiled files and extends them in R so just extracting the particular function might or might not work
The other option is installing an archived version of the RecordLinkage package but then all our users would have to do the same on their machines

**Comment by Akshay-A-Kulkarni** [comment]
_Possible replacement could be the 'stringdist' package_
