### ISSUE TITLE
could not find function "removeGrid"() while viewing metric tabs

### ISSUE THREAD

**Issue by Akshay-A-Kulkarni** [Akshay-A-Kulkarni/MSstatsQCgui_v2.0#2]

**Comment by eralpdogu** [comment]
It should be a function from ggExtra package https://www.rdocumentation.org/packages/ggExtra/versions/0.9/topics/removeGrid

**Comment by Akshay-A-Kulkarni** [comment]
I think i imported that but I'll make sure !
